const choices = [
  {
    text: "İskoçya'da Doğ (Orta)",
    ageRange: { min: 0, max: 1 },
    immediateEffects: { health: 40, money: 800, love: 15, happiness: 25 },
    longTermEffects: [],
  },
  {
    text: "Kanada'da Doğ (Kolay)",
    ageRange: { min: 0, max: 1 },
    immediateEffects: { health: 60, money: 1000, love: 20, happiness: 35 },
    longTermEffects: [],
  },
  {
    text: "Brezilya'da Doğ (Zor)",
    ageRange: { min: 0, max: 1 },
    immediateEffects: { health: 30, money: 300, love: 10, happiness: 10 },
    longTermEffects: [],
  },
  {
    text: "Japonya'da Doğ (Kolay)",
    ageRange: { min: 0, max: 1 },
    immediateEffects: { health: 60, money: 1000, love: 5, happiness: 40 },
    longTermEffects: [],
  },
  {
    text: "Avustralya'da Doğ (Orta)",
    ageRange: { min: 0, max: 1 },
    immediateEffects: { health: 50, money: 500, love: 0, happiness: 5 },
    longTermEffects: [],
  },
  {
    text: "Türkiyede Doğ (Extreme)",
    ageRange: { min: 0, max: 1 },
    immediateEffects: { health: 0, money: 300, love: 0, happiness: 0 },
    longTermEffects: [],
  },
  {
    text: "Amerikada Doğ (Kolay)",
    ageRange: { min: 0, max: 1 },
    immediateEffects: { health: 30, money: 800, love: 30, happiness: 40 },
    longTermEffects: [],
  },
  {
    text: "Almanyada Doğ (Kolay)",
    ageRange: { min: 0, max: 1 },
    immediateEffects: { health: 50, money: 900, love: 10, happiness: 30 },
    longTermEffects: [],
  },
  {
    text: "Hindistanda Doğ (Zor)",
    ageRange: { min: 0, max: 1 },
    immediateEffects: { health: 0, money: 200, love: 0, happiness: 0 },
    longTermEffects: [],
  },
  {
    text: "Evde bir bira demleme kitini deneyin",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: -35, money: -20, love: 0, happiness: 35 },
    longTermEffects: [],
  },
  {
    text: "Bir bitki teraryumu yap ",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -15, love: 0, happiness: 20 },
    longTermEffects: [],
  },
  {
    text: "Gece gökyüzü fotoğrafçılığına başla",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -50, love: 0, happiness: 25 },
    longTermEffects: [],
  },
  {
    text: "Karmaşık bir model uçak kitini tamamla",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -50, love: 0, happiness: 10 },
    longTermEffects: [],
  },
  {
    text: "Sıradışı bir müze keşfet",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -5, love: 0, happiness: 10 },
    longTermEffects: [],
  },
  {
    text: "Bir sokak sanatı turuna çık",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: 0, love: 0, happiness: 5 },
    longTermEffects: [],
  },
  {
    text: "Evde yoga yap",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 15, money: 0, love: 0, happiness: 15 },
    longTermEffects: [],
  },
  {
    text: "Antikalarla dolu bir pazar gez",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -15, love: 0, happiness: 10 },
    longTermEffects: [],
  },
  {
    text: "Ortaçağ tarzı bir yemek pişir",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 5, money: -20, love: 0, happiness: 10 },
    longTermEffects: [],
  },
  {
    text: "Bir doğa yürüyüşüne çık",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 20, money: 0, love: 0, happiness: 15 },
    longTermEffects: [],
  },
  {
    text: "Kendi podcast'ini başlat",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -200, love: 0, happiness: 15 },
    longTermEffects: [],
  },
  {
    text: "Vintage bir kamera ile fotoğraf çekmeyi öğren",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -100, love: 0, happiness: 20 },
    longTermEffects: [],
  },
  {
    text: "Bir komedi kulübünde stand-up yapmayı dene",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: 0, love: 0, happiness: -200 },
    longTermEffects: [],
  },
  {
    text: "Bir çiçek bahçesi kur",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 10, money: -100, love: 0, happiness: 15 },
    longTermEffects: [],
  },
  {
    text: "Fotoğrafçılık öğren",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -50, love: 0, happiness: 10 },
    longTermEffects: [],
  },
  {
    text: "Bir kitap kulübüne katıl",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: 0, love: 10, happiness: 15 },
    longTermEffects: [],
  },
  {
    text: "Blog yazmaya başla",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -10, love: 0, happiness: 15 },
    longTermEffects: [],
  },
  {
    text: "Bir online mağaza aç",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -800, love: 0, happiness: -15 },
    longTermEffects: [{ effect: { money: 200 }, duration: 15, startYear: 3 }],
  },
  {
    text: "Bir belgesel çek",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: -20, money: -600, love: 0, happiness: -20 },
    longTermEffects: [
      { effect: { money: 150, happiness: 10 }, duration: 5, startYear: 1 },
    ],
  },
  {
    text: "Profesyonel bir dansçı olmayı dene",
    ageRange: { min: 18, max: 35 },
    immediateEffects: { health: -5, money: 0, love: 15, happiness: -200 },
    longTermEffects: [
      { effect: { money: 300, happiness: 20 }, duration: 10, startYear: 3 },
    ],
  },
  {
    text: "Kırsal bir alanda yaşamaya başla",
    ageRange: { min: 25, max: 70 },
    immediateEffects: { health: 20, money: -700, love: 0, happiness: 50 },
    longTermEffects: [{ effect: { health: 10 }, duration: 30, startYear: 5 }],
  },
  {
    text: "Evdeki bitkilern bakımını yap",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: 0, love: 0, happiness: 5 },
    longTermEffects: [],
  },
  {
    text: "Haftada bir yeni bir yemek tarifi deneyin",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -5, love: 0, happiness: 5 },
    longTermEffects: [],
  },
  {
    text: "Bir enstrüman çalmayı öğrenin",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 10, money: -100, love: 0, happiness: 15 },
    longTermEffects: [],
  },
  {
    text: "Gönüllü çalışmaya başla",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: 0, love: 5, happiness: 15 },
    longTermEffects: [],
  },
  {
    text: "Pahalı bir hobinin tadını çıkar",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -500, love: 0, happiness: 50 },
    longTermEffects: [],
  },
  {
    text: "Yeni bir dil öğrenmeye başla",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -100, love: 0, happiness: 10 },
    longTermEffects: [],
  },
  {
    text: "Yoga veya meditasyon yapmayı dene",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 25, money: 0, love: 0, happiness: 30 },
    longTermEffects: [],
  },
  {
    text: "Bir spor salonuna kaydol",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -500, love: 0, happiness: 0 },
    longTermEffects: [
      { effect: { health: 20, happiness: 5 }, duration: 10, startYear: 1 },
    ],
  },
  {
    text: "Daha sağlıklı bir beslenme alışkanlığı edin",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 10, money: -200, love: 0, happiness: 0 },
    longTermEffects: [{ effect: { health: 5 }, duration: 20, startYear: 1 }],
  },
  {
    text: "Kendi işini kur",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -3000, love: 0, happiness: -20 },
    longTermEffects: [
      { effect: { money: 1500, happiness: 20 }, duration: 10, startYear: 5 },
    ],
  },
  {
    text: "Yüksek öğrenim için yurtdışına git",
    ageRange: { min: 18, max: 30 },
    immediateEffects: { health: 0, money: -1000, love: 50, happiness: 30 },
    longTermEffects: [
      { effect: { happiness: 50, love: 50 }, duration: 5, startYear: 5 },
    ],
  },
  {
    text: "Bir aile kur",
    ageRange: { min: 20, max: 40 },
    immediateEffects: { health: 0, money: -2000, love: 500, happiness: 30 },
    longTermEffects: [{ effect: { love: -20 }, duration: 20, startYear: 5 }],
  },
  {
    text: "Uzun vadede karlı büyük bir yatırım yap",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -2000, love: 0, happiness: 10 },
    longTermEffects: [{ effect: { money: 2000 }, duration: 10, startYear: 5 }],
  },
  {
    text: "Sağlık sigortası satın al",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 10, money: -20, love: 0, happiness: 10 },
    longTermEffects: [{ effect: { health: 30 }, duration: 20, startYear: 5 }],
  },
  {
    text: "Girişimci ol",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: -10, money: -1000, love: 0, happiness: 20 },
    longTermEffects: [{ effect: { money: 300 }, duration: 15, startYear: 2 }],
  },
  {
    text: "Yeni bir kariyer yoluna gir",
    ageRange: { min: 25, max: 50 },
    immediateEffects: { health: 0, money: -300, love: 0, happiness: 50 },
    longTermEffects: [{ effect: { money: 200 }, duration: 15, startYear: 5 }],
  },
  {
    text: "Yatırım yapmak için bir danışman işe al",
    ageRange: { min: 30, max: 60 },
    immediateEffects: { health: 0, money: -1000, love: 0, happiness: 10 },
    longTermEffects: [{ effect: { money: 250 }, duration: 20, startYear: 1 }],
  },
  {
    text: "Bir müzik grubu kur",
    ageRange: { min: 18, max: 35 },
    immediateEffects: { health: 0, money: -400, love: 10, happiness: 30 },
    longTermEffects: [
      { effect: { money: 100, happiness: 5 }, duration: 5, startYear: 3 },
    ],
  },
  {
    text: "Dünya turuna çık",
    ageRange: { min: 18, max: 50 },
    immediateEffects: { health: 10, money: -1000, love: 0, happiness: 30 },
    longTermEffects: [
      { effect: { happiness: 10 }, duration: 10, startYear: 1 },
    ],
  },
  {
    text: "Sosyal medya fenomeni ol",
    ageRange: { min: 18, max: 22 },
    immediateEffects: { health: 0, money: -100, love: 20, happiness: 25 },
    longTermEffects: [{ effect: { money: 2000 }, duration: 5, startYear: 2 }],
  },
  {
    text: "Bir yoga stüdyosu aç",
    ageRange: { min: 25, max: 50 },
    immediateEffects: { health: 0, money: -1500, love: 0, happiness: 15 },
    longTermEffects: [
      { effect: { money: 300, happiness: 10 }, duration: 15, startYear: 3 },
    ],
  },
  {
    text: "Vegan kafe aç",
    ageRange: { min: 20, max: 50 },
    immediateEffects: { health: 5, money: -1500, love: 10, happiness: 10 },
    longTermEffects: [{ effect: { money: 400 }, duration: 10, startYear: 4 }],
  },
  {
    text: "BISS'te işe başla!",
    ageRange: { min: 19, max: 40 },
    immediateEffects: {
      health: 99999,
      money: 99999,
      love: 99999,
      happiness: 99999,
    },
    longTermEffects: [],
  },
  {
    text: "BISS'te işe başla!",
    ageRange: { min: 19, max: 40 },
    immediateEffects: {
      health: 99999,
      money: 99999,
      love: 99999,
      happiness: 99999,
    },
    longTermEffects: [],
  },
  {
    text: "BISS'te işe başla!",
    ageRange: { min: 19, max: 40 },
    immediateEffects: {
      health: 99999,
      money: 99999,
      love: 99999,
      happiness: 99999,
    },
    longTermEffects: [],
  },
  {
    text: "Organik çiftlik kur",
    ageRange: { min: 25, max: 60 },
    immediateEffects: { health: 10, money: -20000, love: 0, happiness: 15 },
    longTermEffects: [
      { effect: { money: 500, health: 20 }, duration: 25, startYear: 5 },
    ],
  },
  {
    text: "Dans kurslarına git",
    ageRange: { min: 18, max: 50 },
    immediateEffects: { health: 10, money: -200, love: 20, happiness: 20 },
    longTermEffects: [],
  },
  {
    text: "Bir restoran aç",
    ageRange: { min: 25, max: 60 },
    immediateEffects: { health: -5, money: -2000, love: 0, happiness: 10 },
    longTermEffects: [
      { effect: { money: 500, happiness: 10 }, duration: 10, startYear: 1 },
    ],
  },
  {
    text: "Bir çiftlik işlet",
    ageRange: { min: 25, max: 80 },
    immediateEffects: { health: 20, money: -2000, love: 0, happiness: 15 },
    longTermEffects: [
      { effect: { money: 300, happiness: 5 }, duration: 20, startYear: 3 },
    ],
  },
  {
    text: "Bir teknoloji startup'ı kur",
    ageRange: { min: 22, max: 45 },
    immediateEffects: { health: 0, money: -4000, love: 0, happiness: -5 },
    longTermEffects: [
      { effect: { money: 2000, happiness: 15 }, duration: 10, startYear: 2 },
    ],
  },
  {
    text: "Bir hayır kurumu başlat",
    ageRange: { min: 30, max: 80 },
    immediateEffects: { health: 5, money: -1000, love: 10, happiness: 25 },
    longTermEffects: [
      { effect: { happiness: 10 }, duration: 20, startYear: 21 },
    ],
  },
  {
    text: "Uzun süre bilgisayar başında çalış",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: -30, money: 500, love: 0, happiness: 10 },
    longTermEffects: [],
  },
  {
    text: "Tek seferlik stresli bir işi al",
    ageRange: { min: 25, max: 50 },
    immediateEffects: { health: -30, money: 500, love: 0, happiness: -30 },
    longTermEffects: [],
  },
  {
    text: "Evcil hayvan olarak egzotik bir hayvan besle",
    ageRange: { min: 18, max: 50 },
    immediateEffects: { health: -50, money: -150, love: 10, happiness: 10 },
    longTermEffects: [],
  },
  {
    text: "Evden çalış. Ancak ergonomik olmayan bir setup kullan.",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: -15, money: 0, love: 0, happiness: 5 },
    longTermEffects: [],
  },
  {
    text: "Gecleri arkadaşlarınla uzun süreli film maratonları yap",
    ageRange: { min: 18, max: 35 },
    immediateEffects: { health: -25, money: 0, love: 5, happiness: 25 },
    longTermEffects: [],
  },
  {
    text: "Yoga sınıfında yeni bir poz dene",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: -200, money: 0, love: 0, happiness: 15 },
    longTermEffects: [],
  },
  {
    text: "Çevrimiçi arkadaşlık sitesine katıl",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -50, love: 20, happiness: 10 },
    longTermEffects: [],
  },
  {
    text: "İşini büyütmek için her şeyi riske at",
    ageRange: { min: 25, max: 50 },
    immediateEffects: { health: 0, money: 10000, love: 0, happiness: 100 },
    longTermEffects: [],
  },
  {
    text: "İşini büyütmek için her şeyi riske at",
    ageRange: { min: 25, max: 50 },
    immediateEffects: { health: 0, money: -10000, love: 0, happiness: -100 },
    longTermEffects: [],
  },
  {
    text: "Özel hayatını ikinci plana at",
    ageRange: { min: 30, max: 60 },
    immediateEffects: { health: -5, money: 200, love: -50, happiness: -25 },
    longTermEffects: [
      { effect: { money: 300, happiness: 5 }, duration: 15, startYear: 1 },
    ],
  },

  {
    text: "Yoğun bir iş hayatına adım at",
    ageRange: { min: 20, max: 50 },
    immediateEffects: { health: -30, money: 300, love: -30, happiness: -30 },
    longTermEffects: [{ effect: { money: 300 }, duration: 15, startYear: 2 }],
  },
  {
    text: "Uluslararası bir projede çalış",
    ageRange: { min: 30, max: 60 },
    immediateEffects: { health: 0, money: 500, love: -30, happiness: 10 },
    longTermEffects: [{ effect: { money: 500 }, duration: 3, startYear: 1 }],
  },
  {
    text: "Romantik bir şehirde yaşamaya başla",
    ageRange: { min: 18, max: 99 },
    immediateEffects: { health: 0, money: -500, love: 50, happiness: 30 },
    longTermEffects: [],
  },
];

export default choices;
